from django.shortcuts import render
from django.http import HttpResponse

def home(request):
  return render (request, 'home.html')

def about(request):
  return render(request, 'about.html')

def hero_detail(request, hero):
  return render(request, 'heroes/detail.html', {'hero': hero})

class Hero:
  def __init__(self, name, role, rating, description, weapon, abilities, background, portrait):
    self.name = name
    self.role = role
    self.rating = rating
    self.description = description
    self.weapon = weapon
    self.abilities = abilities
    self.background = background
    self.portrait = portrait

heroes = [
  Hero('Ana', 'Support', 3, "Ana’s versatile arsenal allows her to affect heroes all over the battlefield. Her Biotic Rifle rounds and Biotic Grenades heal allies and damage or impair enemies; her sidearm tranquilizes key targets, and Nano Boost gives one of her comrades a considerable increase in power.", 'Biotic Rifle', 'Sleep Dart, Biotic Grenade, Nano Boost', 'https://d1u1mce87gyfbn.cloudfront.net/hero/ana/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/ana/hero-select-portrait.png'),
  Hero('Ashe', 'Damage', 2, "Ashe quickly fires her rifle from the hip or uses her weapon’s aim-down sights to line up a high damage shot. She blasts enemies by throwing dynamite, and her coach gun packs enough punch to put some distance between her and her foes. And Ashe is not alone, as she can call on her omnic ally Bob, to join the fray when the need arises.", "The Viper - Rifle", "Coach Gun, Dynamite, B.O.B.","https://d1u1mce87gyfbn.cloudfront.net/hero/ashe/idle-video.webm", "https://d1u1mce87gyfbn.cloudfront.net/hero/ashe/hero-select-portrait.png"),
  Hero('Baptiste', "Support", 3, "Baptiste wields an assortment of experimental devices and weaponry to keep allies alive and eliminate threats under fierce conditions. A battle-hardened combat medic, he is just as capable of saving lives as he is taking out the enemy.", 'Biotic Launcher', 'Regenerative Burst, Immortality Field, Exo Boots, Amplification Matrix', 'https://d1u1mce87gyfbn.cloudfront.net/hero/baptiste/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/baptiste/hero-select-portrait.png'),
  Hero('Bastion', 'Damage', 1, "Repair protocols and the ability to transform between stationary Assault, mobile Recon and devastating Tank configurations provide Bastion with a high probability of victory.", 'Configuration: Sentry, Configuration: Recon', 'Self-Repair, Reconfigure, Ironclad, Configuration: Tank', 'https://d1u1mce87gyfbn.cloudfront.net/hero/bastion/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/bastion/hero-select-portrait.png'),
  Hero('Brigitte', 'Support', 1, "Brigitte specializes in armor. She can throw Repair Packs to heal teammates, or automatically heal nearby allies when she damages foes with her Flail. Her Flail is capable of a wide swing to strike multiple targets, or a Whip Shot that stuns an enemy at range. When entering the fray, Barrier Shield provides personal defense while she attacks enemies with Shield Bash. Brigitte’s ultimate ability, Rally, gives her a substantial short-term boost of speed and provides long-lasting armor to all her nearby allies.", 'Rocket Flail', 'Repair Pack, Whip Shot, Barrier Shield, Shield Bash, Inspire, Rally', 'https://d1u1mce87gyfbn.cloudfront.net/hero/brigitte/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/brigitte/hero-select-portrait.png'),
  Hero('Cassidy', 'Damage', 2, "Armed with his Peacekeeper revolver, Cassidy takes out targets with deadeye precision and dives out of danger with eagle-like speed.", 'Peacekeeper', 'Combat Roll, Flashbang, Deadeye', 'https://d1u1mce87gyfbn.cloudfront.net/hero/cassidy/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/cassidy/hero-select-portrait.png'),
  Hero('DVa', 'Tank', 2, "D.Va’s mech is nimble and powerful—its twin Fusion Cannons blast away with autofire at short range, and she can use its Boosters to barrel over enemies and obstacles, or deflect attacks with her projectile-dismantling Defense Matrix.", 'Fusion Cannons, Light Gun', 'Boosters, Defense Matrix, Micro Missiles, Call Mech, Eject, Self-Destruct', 'https://d1u1mce87gyfbn.cloudfront.net/hero/dva/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/dva/hero-select-portrait.png'),
  Hero('Doomfist', 'Damage', 3, "Doomfist’s cybernetics make him a highly-mobile, powerful frontline fighter. In addition to dealing ranged damage with his Hand Cannon, Doomfist can slam the ground, knock enemies into the air and off balance, or charge into the fray with his Rocket Punch. When facing a tightly packed group, Doomfist leaps out of view, then crashes down to earth with a spectacular Meteor Strike.", 'Hand Cannon', 'Seismic Slam, Rising Uppercut, Rocket Punch, Meteor Strike', 'https://d1u1mce87gyfbn.cloudfront.net/hero/doomfist/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/doomfist/hero-select-portrait.png'),
  Hero('Echo', 'Damage', 2, "Echo is an evolutionary robot programmed with a rapidly adapting artificial intelligence, versatile enough to fill multiple battlefield combat roles.", 'Tri-shot', 'Sticky Bombs, Flight, Focusing Beam, Glide, Duplicate', 'https://d1u1mce87gyfbn.cloudfront.net/hero/echo/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/echo/hero-select-portrait.png'),
  Hero('Genji', 'Damage', 3, "Genji flings precise and deadly Shuriken at his targets, and uses his technologically-advanced katana to deflect projectiles or deliver a Swift Strike that cuts down enemies.", 'Shuriken, Fan of Blades', 'Deflect, Swift Strike, Cyber Agility, Dragonblade', 'https://d1u1mce87gyfbn.cloudfront.net/hero/genji/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/genji/hero-select-portrait.png'),
  Hero('Hanzo', 'Damage', 3, "Hanzo’s versatile arrows can reveal his enemies or fragment to strike multiple targets. He can scale walls to fire his bow from on high, or summon a titanic spirit dragon.", 'Storm Bow', 'Storm Arrows, Sonic Arrow, Lunge, Wall Climb, Dragonstrike', 'https://d1u1mce87gyfbn.cloudfront.net/hero/hanzo/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/hanzo/hero-select-portrait.png'),
  Hero('Junkrat', 'Damage', 2, "Junkrat’s area-denying armaments include a Frag Launcher that lobs bouncing grenades, Concussion Mines that send enemies flying, and Steel Traps that stop foes dead in their tracks.", 'Frag Launcher', 'Concussion Mine, Steel Trap, Total Mayhem, RIP-Tire', 'https://d1u1mce87gyfbn.cloudfront.net/hero/junkrat/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/junkrat/hero-select-portrait.png'),
  Hero('Lúcio', 'Support', 2, "On the battlefield, Lúcio’s cutting-edge Sonic Amplifier buffets enemies with projectiles and knocks foes back with blasts of sound. His songs can both heal his team or boost their movement speed, and he can switch between tracks on the fly.", 'Sonic Amplifier', 'Crossfade, Soundwave, Amp It Up, Soundwave, Wall Ride, Sound Barrier', 'https://d1u1mce87gyfbn.cloudfront.net/hero/lucio/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/lucio/hero-select-portrait.png'),
  Hero('Mei', 'Damage', 3, "Mei’s weather-altering devices slow opponents and protect locations. Her Endothermic Blaster unleashes damaging icicles and frost streams, and she can Cryo-Freeze herself to guard against counterattacks, or obstruct the opposing team's movements with an Ice Wall.", 'Endothermic Blaster, Icicle', 'Cryo-Freeze, Ice Wall, Blizzard', 'https://d1u1mce87gyfbn.cloudfront.net/hero/mei/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/mei/hero-select-portrait.png'),
  Hero('Mercy', 'Support', 1, "Mercy’s Valkyrie Suit helps keep her close to teammates like a guardian angel; healing, resurrecting or strengthening them with the beams emanating from her Caduceus Staff.", 'Caduceus Staff, Caduceus Blaster', 'Guardian Angel, Resurrect, Angelic Descent, Regeneration, Valkyrie', 'https://d1u1mce87gyfbn.cloudfront.net/hero/mercy/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/mercy/hero-select-portrait.png'),
  Hero('Moira', 'Support', 2, "Moira’s biotic abilities enable her to contribute healing or damage in any crisis. While Biotic Grasp gives Moira short-range options, her Biotic Orbs contribute longer-range, hands-off damage and healing; she can also Fade to escape groups or remain close to allies in need of support. Once she’s charged Coalescence, Moira can save multiple allies from elimination at once or finish off weakened enemies.", 'Biotic Grasp', 'Biotic Orb, Fade, Coalescence', 'https://d1u1mce87gyfbn.cloudfront.net/hero/moira/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/moira/hero-select-portrait.png'),
  Hero('Orisa', 'Tank', 2, "Orisa serves as the central anchor of her team, and defends her teammates from the frontline with a protective barrier. She can attack from long range, fortify her own defenses, launch graviton charges to slow and move enemies, and deploy a Supercharger to boost the damage output of multiple allies at once.", 'Fusion Driver', 'Protective Barrier, Fortify, Supercharger, Halt!', 'https://d1u1mce87gyfbn.cloudfront.net/hero/orisa/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/orisa/hero-select-portrait.png'),
  Hero('Pharah', 'Damage', 1, "Soaring through the air in her combat armor, and armed with a launcher that lays down high-explosive rockets, Pharah is a force to be reckoned with.", 'Rocket Launcher', 'Jump Jet, Concussive Blast, Hover Jet, Barrage', 'https://d1u1mce87gyfbn.cloudfront.net/hero/pharah/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/pharah/hero-select-portrait.png'),
  Hero('Reaper', 'Damage', 1, "Hellfire Shotguns, the ghostly ability to become immune to damage, and the power to step between shadows make Reaper one of the deadliest beings on Earth.", 'Hellfire Shotguns', 'Wraith Form, Shadow Step, The Reaping, Death Blossom', 'https://d1u1mce87gyfbn.cloudfront.net/hero/reaper/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/reaper/hero-select-portrait.png'),
  Hero('Reinhardt', 'Tank', 1, "Clad in powered armor and swinging his hammer, Reinhardt leads a rocket-propelled charge across the battleground and defends his squadmates with a massive energy barrier.", 'Rocket Hammer', 'Charge, Fire Strike, Barrier Field, Steadfast, Earthshatter', 'https://d1u1mce87gyfbn.cloudfront.net/hero/reinhardt/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/reinhardt/hero-select-portrait.png'),
  Hero('Roadhog', 'Tank', 1, "Roadhog uses his signature Chain Hook to pull his enemies close before shredding them with blasts from his Scrap Gun. He’s hardy enough to withstand tremendous damage, and can recover his health with a short breather.", 'Scrap Gun', 'Chain Hook, Take a Breather, Whole Hog', 'https://d1u1mce87gyfbn.cloudfront.net/hero/roadhog/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/roadhog/hero-select-portrait.png'),
  Hero('Sigma', 'Tank', 3, "Sigma is an eccentric astrophysicist and volatile tank who gained the power to control gravity in an orbital experiment gone wrong. Manipulated by Talon and deployed as a living weapon, Sigma’s presence on the battlefield cannot be ignored.", 'Hyperspheres', 'Kinetic Grasp, Accretion, Experimental Barrier, Gravitic Flux', 'https://d1u1mce87gyfbn.cloudfront.net/hero/sigma/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/sigma/hero-select-portrait.png'),
  Hero('Soldier: 76', 'Damage', 1, "Armed with cutting-edge weaponry, including an experimental pulse rifle that’s capable of firing spirals of high-powered Helix Rockets, Soldier: 76 has the speed and support know-how of a highly trained warrior.", 'Heavy Pulse Rifle', 'Sprint, Biotic Field, Helix Rockets, Tactical Visor', 'https://d1u1mce87gyfbn.cloudfront.net/hero/soldier-76/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/soldier-76/hero-select-portrait.png'),
  Hero('Sombra', 'Damage', 3, "Stealth and debilitating attacks make Sombra a powerful infiltrator. Her hacking can disrupt her enemies, ensuring they're easier to take out, while her EMP provides the upper hand against multiple foes at once. Sombra’s ability to Translocate and camouflage herself makes her a hard target to pin down.", 'Machine Pistol', 'Translocator, Stealth, Hack, Opportunist, EMP', 'https://d1u1mce87gyfbn.cloudfront.net/hero/sombra/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/sombra/hero-select-portrait.png'),
  Hero('Symmetra', 'Damage', 2, "SSymmetra utilizes her Photon Projector to dispatch adversaries, shield her associates, construct teleportation pads and deploy particle-blasting Sentry Turrets.", 'Photon Projector', 'Sentry Turret, Teleporter, Photon Barrier', 'https://d1u1mce87gyfbn.cloudfront.net/hero/symmetra/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/symmetra/hero-select-portrait.png'),
  Hero('Torbjörn', 'Damage', 2, "Torbjörn’s extensive arsenal includes a rivet gun, hammer, and a personal forge that he can use to build turrets.", 'Rivet Gun, Forge Hammer', 'Deploy Turret, Overload, Molten Core', 'https://d1u1mce87gyfbn.cloudfront.net/hero/torbjorn/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/torbjorn/hero-select-portrait.png'),
  Hero('Tracer', 'Damage', 2, 'Toting twin pulse pistols, energy-based time bombs, and rapid-fire banter, Tracer is able to "blink" through space and rewind her personal timeline as she battles to right wrongs the world over.', 'Pulse Pistols', 'Blink, Recall, Pulse Bomb', 'https://d1u1mce87gyfbn.cloudfront.net/hero/tracer/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/tracer/hero-select-portrait.png'),
  Hero('Widowmaker', 'Damage', 2, "Widowmaker equips herself with whatever it takes to eliminate her targets, including mines that dispense poisonous gas, a visor that grants her squad infra-sight, and a powerful sniper rifle that can fire in fully-automatic mode.", 'Widow’s Kiss, Sniper Mode', 'Grappling Hook, Venom Mine, Infra-Sight', 'https://d1u1mce87gyfbn.cloudfront.net/hero/widowmaker/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/widowmaker/hero-select-portrait.png'),
  Hero('Winston', 'Tank', 2, "Winston wields impressive inventions—a jump pack, electricity-blasting Tesla Cannon, portable shield projector and more—with literal gorilla strength.", 'Tesla Cannon', 'Jump Pack, Barrier Projector, Primal Rage', 'https://d1u1mce87gyfbn.cloudfront.net/hero/winston/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/winston/hero-select-portrait.png'),
  Hero('Wrecking Ball', 'Tank', 3, "Wrecking Ball rolls across the battlefield, using his arsenal of weapons and his mech’s powerful body to crush his enemies.", 'Quad Cannons', 'Grappling Claw, Roll, Piledriver, Adaptive Shield, Minefield', 'https://d1u1mce87gyfbn.cloudfront.net/hero/wrecking-ball/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/wrecking-ball/hero-select-portrait.png'),
  Hero('Zarya', 'Tank', 3, "Deploying powerful personal barriers that convert incoming damage into energy for her massive Particle Cannon, Zarya is an invaluable asset on the front lines of any battle.", 'Particle Cannon', 'Particle Barrier, Projected Barrier, Energy, Graviton Surge', 'https://d1u1mce87gyfbn.cloudfront.net/hero/zarya/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/zarya/hero-select-portrait.png'),
  Hero('Zenyatta', 'Support', 3, "Zenyatta calls upon orbs of harmony and discord to heal his teammates and weaken his opponents, all while pursuing a transcendent state of immunity to damage.", 'Orb of Destruction', 'Orb of Discord, Orb of Harmony, Transcendence', 'https://d1u1mce87gyfbn.cloudfront.net/hero/zenyatta/idle-video.webm', 'https://d1u1mce87gyfbn.cloudfront.net/hero/zenyatta/hero-select-portrait.png'),
]

def hero_list(request):
  return render(request, 'heroes/list.html', {'heroes': heroes})