# Generated by Django 4.1 on 2022-09-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=8)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('weapon', models.CharField(max_length=50)),
                ('abilties', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('portrait', models.CharField(max_length=200)),
            ],
        ),
    ]
