# Generated by Django 4.1 on 2022-09-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='abilties',
            new_name='abilities',
        ),
    ]
